name: Desplegar casino-backend en EKS (CI/CD)
on:
  push:
    branches: [ deploy ]
  workflow_dispatch:
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.EKS_CLUSTER }}
  SERVICE_NAME: ${{ vars.ECR_REPOSITORY }}
  IMAGE_VERSION: "v1.1.0"
jobs:

  #Primera etapa: TESTS
  test: 
    name: Pruebas unitarias backend(pytest)
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        service: [bonos-service, apuestas-service, estadisticas-service]
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Instalar dependencias y correr pytest
        working-directory: ${{ matrix.service }}
        run: |
          pyton -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 1. Descargar el codigo del repo
        uses: actions/checkout@v4

      - name: 2. Configurar credenciales de AWS (temporales del lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Login en Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 4. Construir y subir la imagen
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$REGISTRY/$SERVICE_NAME:$IMAGE_VERSION" -t "$REGISTRY/$SERVICE_NAME:latest" -t "$REGISTRY/$SERVICE_NAME:$IMAGE_TAG" .
          docker push "$REGISTRY/$SERVICE_NAME:$IMAGE_VERSION"
          docker push "$REGISTRY/$SERVICE_NAME:latest"
          docker push "$REGISTRY/$SERVICE_NAME:$IMAGE_TAG"

      - name: 5. Instalar kubectl en el runner
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: 6. Conectar kubectl al cluster
        run: aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"

      - name: 6.1 Crear/actualizar ConfigMap con el esquema SQL
        run: |
          kubectl create configmap postgres-init-sql \
            --from-file=01-init.sql=db/init.sql \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: 6.2 Desplegar PostgreSQL si no existe
        run: |
          kubectl apply -f k8s/postgres.yaml
          kubectl rollout status deployment/postgres --timeout=120s
      - name: 7. Desplegar el Deployment y el Service
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          sed -i "s|<ACCOUNT_ID>|$ACCOUNT_ID|g; s|<REGION>|$AWS_REGION|g; s|:latest|:$IMAGE_TAG|g" "k8s/deployment.yaml"
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: 8. Esperar al rollout y mostrar el resultado
        run: |
          kubectl rollout status deployment/$SERVICE_NAME --timeout=180s
          kubectl get pods -o wide -l app=$SERVICE_NAME
      
      - name: 9. Resumen de versiones publicadas
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          echo "### Imagen publicada en ECR" >> $GITHUB_STEP_SUMMARY
          echo "- \`$REGISTRY/$SERVICE_NAME:$IMAGE_VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`$REGISTRY/$SERVICE_NAME:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`$REGISTRY/$SERVICE_NAME:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY